WIDTH = 20
HEIGHT = 20

# Size of the maze
MAZE_WIDTH = 101
MAZE_HEIGHT = 101

# Size of a tile
TILE_WIDTH = 32
TILE_HEIGHT = 32

SURFACE_WIDTH = TILE_WIDTH * MAZE_WIDTH
SURFACE_HEIGHT = TILE_HEIGHT * MAZE_HEIGHT


# Size of the game play area
PLAY_WIDTH = WIDTH * TILE_WIDTH
PLAY_HEIGHT = HEIGHT * TILE_HEIGHT
MID_PLAY_WIDTH = PLAY_WIDTH // 2
MID_PLAY_HEIGHT = PLAY_HEIGHT // 2
RIGHT_SCROLL_LIM = SURFACE_WIDTH - MID_PLAY_WIDTH
LEFT_SCROLL_LIM = MID_PLAY_WIDTH - 1
TOP_SCROLL_LIM = MID_PLAY_HEIGHT - 1
BOT_SCROLL_LIM = SURFACE_HEIGHT - MID_PLAY_HEIGHT

# Size of the score/state area
HEAD_WIDTH = WIDTH * TILE_WIDTH
HEAD_HEIGHT = TILE_HEIGHT

# Size of the game window
BOARD_WIDTH = PLAY_WIDTH
BOARD_HEIGHT = PLAY_HEIGHT + HEAD_HEIGHT


WINDOW_RIGHT_MAX = SURFACE_WIDTH - TILE_WIDTH
WINDOW_BOTTOM_MAX = SURFACE_HEIGHT - TILE_HEIGHT
WIDTH_CENTER = SURFACE_WIDTH // 2
HEIGHT_CENTER = SURFACE_HEIGHT // 2


BACKGROUND_COLOR = (156, 102, 47)
